### ISSUE TITLE
unevaluatedProperties: Properties matched by externalized schema are not considered

### ISSUE THREAD

**Issue by holgpar** [harrel56/json-schema#108]
Hi,

I found that `unevaluatedProperties" does not seem to work in combination with an externalized sub-schema:

```json
{
    "type": "object",
    "properties": {
        "build": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "external.json"
                },
                {
                    "properties": {
                        "active": {
                            "type": "boolean"
                        }
                    }
                }
            ],
            "unevaluatedProperties": false
        }
    }
}
```

Validation will fail here if a property is only matched by "external.json" due to "unevaluatedProperties". If I inline the content of "external.json" validation passes.

**Comment by harrel56** [comment]
Hi, I checked this case online (https://harrel.dev/json-schema) and it indeed seems to be broken - but I checked the same case locally and it looks to be fixed. I believe with version `1.4.3` came a fix related to unevaluatedProperties. If you don't use this version please try updating - let me know if this works for you

**Comment by holgpar** [comment]
You are right. I was not using the latest version. My bad. With `1.4.3` it looks good.

**Comment by harrel56** [comment]
Nice, glad it worked!
