### ISSUE TITLE
Custom format evaluation

### ISSUE THREAD

**Issue by awgymer** [harrel56/json-schema#120]
Is it possible to extend the format validation to cusom `format` values?

If I follow the docs I think it might be possible by copying some of the code from `FormatEvaluatorFactory` and making a custom factory which implements the validation for the extra formats and then using that like so:
```
new ValidatorFactory().withEvaluatorFactory(EvaluatorFactory.compose(customFactory, new FormatEvaluatorFactory()));
```

Slightly related I was trying to follow the custom keywords evaluator example in the readme but I was a bit confused as I thought that it was only intended to run for strings but then this bit seems to imply it will return a success for anything that is a string without actually doing the contians check? Should it be `(!node.isString())`?
```
/* To stay consistent with other keywords, types not applicable to this keyword should succeed */
        if (node.isString()) {
            return Evaluator.Result.success();
        }
```

**Comment by harrel56** [comment]
> Should it be (!node.isString())?

You are totally right, thanks for finding it!

> Is it possible to extend the format validation to cusom format values?

It should be relatively easy to achieve. But it might a little bit trickier than it seems as you want to support exactly the same keyword (`format`) in 2 EvaluatorFactories. I think such custom factory can be implemented based on what is already in docs:

```java
class CustomEvaluatorFactory implements EvaluatorFactory {
    @Override
    public Optional<Evaluator> create(SchemaParsingContext ctx, String fieldName, JsonNode schemaNode) {
        if ("format".equals(fieldName) && schemaNode.isString() && "customFormat".equals(schemaNode.asString())) {
            return Optional.of(new CustomFormatEvaluator());
        }
        return Optional.empty();
    }
}
```

That way you will only create evaluator when you have a field with name = `format` with value = `customFormat`. You could add more custom formats by following this pattern. Then if you register this factory by calling:
```java
new ValidatorFactory().withEvaluatorFactory(EvaluatorFactory.compose(customFactory, new FormatEvaluatorFactory()));
```
it should work as you expect.

It is worth stating that by such registration/configuration you would have following list/collection of evaluator factories:
1. CustomEvaluatorFactory
2. FormatEvaluatorFactory
3. Draft2020EvaluatorFactory (or 2019 draft variant)

The ordering here is important as it will only query the next factory only if the previous one returned `Optional.empty()`. 

Hopefully it's a bit clearer now, but let me know if there is anything more that needs clarification

**Comment by nvnieuwk** [comment]
Thank you for this thorough explanation! I've managed to implement this :partying_face:

**Comment by harrel56** [comment]
> Thank you for this thorough explanation! I've managed to implement this 🥳

Glad that it was helpful! Probably I could incorporate some of the details into readme/docs.

@awgymer please let me know if there is anything else to be done in scope of this issue. If not, I'm gonna close it.

**Comment by awgymer** [comment]
As Nicolas says we have an implementation now so I think this issue can be closed. I have just one question about the behaviour with multiple evaluators. 

You say that the first one returned is chosen, but can a field have two evaluators for different keywords?

**Comment by harrel56** [comment]
> but can a field have two evaluators for different keywords?

Not sure what you mean - could you elaborate or provide some example?

**Comment by awgymer** [comment]
So can we have a custom evaluator that checks for field name "format" and does something but then also one that checks for a custom keyword say "palindrome" and checks that as well as the one that checks format? Or will the first evaluator matched be the only one used?

**Comment by harrel56** [comment]
The first evaluator matched will be the only one used. I guess the main reason for such behavior is being able to override default evaluators provided with default `EvaluatorFactory` instances - so you can for example provide your own implementation for `type` keyword while keeping other keywords default implementation.

So if you have:
```js
{
  "format": "palindrome"
}
```
the first thing that matches this keyword & keyword-value pair will be used. Each such pair can have 0 or 1 evaluator attached.

In current state, if that's what you want to achieve, you would need to detect (in `EvaluatorFactory`) that for such keyword & keyword-value pair you want to provide more than 1 evaluator - and then provide such evaluator implementation that would basically compose multiple evaluators. It might be trickier if some of the evaluators that you want to attach are part of 3rd party code.

**Comment by awgymer** [comment]
Sorry I think I should have been clearer in my example. What we have is eg 

```
{
    "format": "string",
    "palindrome" true
}
```

And I am wondering if an evaluator that checks `format` and one that separately does something with the Boolean `palindrome` will both be applied? 

I think from your answer and the docs that they will, but I wanted to clarify.

**Comment by harrel56** [comment]
PS. Just updated the "Adding custom keywords" readme section - mainly with what was already said here.

And yes, it would perfectly fine to provide 2 different evaluators for "format" & "palindrome" keywords. And these 2 evaluators would ofc operate on the same string instance (or any other type, whichever you choose to support) during validation process.
