### ISSUE TITLE
Getting the values that throw errors

### ISSUE THREAD

**Issue by nvnieuwk** [harrel56/json-schema#124]
Hi is it possible somehow to get the values that are throwing errors?

Or would it be possible to add this to the `Error` class:
```
def Validator.Result result = this.validator.validate(this.schema, input)
def List<String> = errorValues = result.getErrors().collect { it.getValue() }
```

We would like to add this to the start of the error messages for the user convenience.

Thanks!
-Nicolas

**Comment by harrel56** [comment]
Hi, unfortunately there is no straightforward method to get those values. But you can easily compute them as `instanceLocation` is provided in the error object. This is a simple JSON pointer which you can use to get the value on which the error occurred.

I don't know which JSON provider you use but for example Jackson has built in support for JSON pointers: 
```java
jacksonNode.at(JsonPointer.compile(instanceLocation))
```
where jacksonNode is instance of `JsonNode` from Jackson package.

**Comment by nvnieuwk** [comment]
Hi, thank you for the explanation. We currently use `org.json`, I'll need to have a look how to access the value there :)

**Comment by harrel56** [comment]
Probably you already found it, but here's what I found: https://www.javadoc.io/doc/org.json/json/20211205/org/json/JSONPointer.html

Seems like it should do the job?

**Comment by nvnieuwk** [comment]
Thank you! This worked perfectly :partying_face:

**Comment by nvnieuwk** [comment]
For reference later:

```
String instanceLocation = error.getInstanceLocation()
JSONPointer pointer = new JSONPointer(instanceLocation)
String value = pointer.queryFrom(rawJson)
```

Where `rawJson` is of type `org.json.JSONObject` or `org.json.JSONArray`
