### ISSUE TITLE
Getting the annotations without validating

### ISSUE THREAD

**Issue by nvnieuwk** [harrel56/json-schema#125]
Hi!

Would it be possible to somehow add a way to get the annotations without validating? We have several annotations in our schemas like `help_text`, `description`, `errorMessage`...

For the first two we would like to create a help screen for the users to easily see the options for the schemas, but that needs to happen without actually validating anything

For `errorMessage` we would like it to overwrite the current error message (that on it's own is no problem), but no annotations are returned when the validation isn't succesful.

Maybe something like:
```
validator = new ValidatorFactory()
annotations = validator.getAnnotations(schemaString)
```

Do you see this as a possibility?

Thanks!
-Nicolas

**Comment by harrel56** [comment]
Yeah, I believe there will be a couple of ways to achieve this. One would be creating your own Dialect implementation which has validation vocabulary turned off - probably there also would be need to provide a modified version of a meta-schema. Can't elaborate on it more RN, I could provide more details later today.

**Comment by nvnieuwk** [comment]
Thank you, that would be awesome!

**Comment by nvnieuwk** [comment]
Thanks @harrel56! This explanation is very clear. I'll let you know how it went once got around to implementing it :)

**Comment by nvnieuwk** [comment]
I've managed to find the errorMessages using the JSON pointer method you told me in #124. I've also tried this and it works perfectly, so thank you for your explanation!
