### ISSUE TITLE
Gson < 2.10 causes a NoSuchMethodError

### ISSUE THREAD

**Issue by vintaerj** [harrel56/json-schema#249]
Hello,

I noticed that using a Gson provider with version < `2.10` causes a` NoSuchMethodError` when loading schemas.

This error is related to the use of the method `asList` in `JsonArray` class. This method was initially introduced from the version `2.10` of GSON: https://github.com/google/gson/blob/main/gson/src/main/java/com/google/gson/JsonArray.java#L415.

**Comment by harrel56** [comment]
Hi @vintaerj, this is a really interesting finding, thanks! Using this newer API is not necessary, I'm going to switch to something more compatible so older Gson versions can be used.

**Comment by harrel56** [comment]
Just released version [1.7.2](https://github.com/harrel56/json-schema/releases/tag/1.7.2) and now it should work for older Gson versions (`2.0` and newer, but it is still not explicitly stated anywhere - I'm going to work on defining supported version ranges for each JSON provider in https://github.com/harrel56/json-schema/issues/253).
