### ISSUE TITLE
Sanitization of $id field

### ISSUE THREAD

**Issue by harrel56** [harrel56/json-schema#66]
Passing a value to an `$id` field which is not a valid URI will fail. Maybe it's worth to be less strict here:
- ~~trimming whitespaces~~
- ~~URI encoding other problematic chars~~
- fragments are not allowed by spec (only empty fragments are allowed ATM ~~but why not be more restrictive~~) - https://json-schema.org/draft/2020-12/json-schema-core#name-the-id-keyword
- ~~similar for `$schema`?~~

**Comment by kool79** [comment]
IMHO you should not do more than required by original specification. The library should assume that provided schema is corect. Optionally, if you still want to do that, it should be controlled by some feature flags like 'relaxed' mode. 
 My reason is: we  have a many libs for schema verifications. If someone use your library to create and debug schema-file, then this file should work with all other libraries and should match to standard. But with such smart fixes (sanitizations) there is a risk to create wrong schema.

**Comment by harrel56** [comment]
> IMHO you should not do more than required by original specification.

Yeah, I think I got a bit carried away by looking how other implementations handle such cases. Specification does not mention handling (modifying, sanitazing) `$id` field, so adding such things could lead to confusion and/or potential errors (as you mentioned).

Summarizing: no trimming and encoding. Value of `$id` field should be expected to be a valid URI, potentially already encoded by schema creator. So I guess the only thing left is to disallow URIs with non-empty fragments :)

PS Another thing that occurred to me: URL encoding can be done by using lower or upper case letters (`%2f` vs `%2F`), but this is more concerning the way how schemas are resolved. Also seems like a unusual edge case, so not gonna bother with it for now.

**Comment by kool79** [comment]
Abour URIs. 
As I remember, in URI the only parts which are case-insensite are scheme (https:) and domain-name. While others are case-sensitive. If speak about percent-encoding, than the RFR3986 recommends to use upper-case for percent-encoding.  But it is recommendation only and you can have lower-case in input schemas.

Actually all those differences already handled in the java URI class. I recomment to NOT use the String class instead URI. Use the URI where URI expected.  This will help you to not care about case-sensitivity of different parts of URI.  
As an example, you need to refactor/rewrite implemenmtation of  SchemaRegistry store. In State class you use the 
`Map<String, Schema>' to store schemas, It should be replaced with  `Map<URI, Schema>`

```java
String stringUri1 = "HTTPS://aaa.com/%2C";
String stringUri1 = "HTTPS://aaa.com/%2c";
URI uri1 = URI.create(stringUri1);
URI uri2 = URI.create(stringUri2);

//for 'string' representation:
System.out.println(stringUri1.hashCode() == stringUri2.hashCode())  //false
System.out.println(stringUri1.equals(stringUri2))  //false
System.out.println(uri1.toString().hashCode() == uri2.toString().hashCode()) //false

// for URI:
System.out.println(uri1.hashCode() == uri2.hashCode()) //true
System.out.println(uri1.equals(uri2)) //true
System.out.println(uri1.compareTo(uri2)==0) //true
```

**Comment by harrel56** [comment]
Nice, should've known that URI class is smart in these cases. Interestingly enough, I believe I started out with maps with URIs as keys, but this approach has its downsides too - don't remember exactly why the switch to Strings occurred but I'm positive it had to do with URI class being too restrictive. I doesn't allow for certain fragments structure which are expected to be valid per JSON Schema spec. 

So fixing this is not as straightforward as it might seem. Probably the whole `SchemaRegistry` would need to be reworked - keeping this issue in mind but wouldn't consider it high priority though
