### ISSUE TITLE
Please add the schema $id to Error class when we have InvalidSchemaException

### ISSUE THREAD

**Issue by kool79** [harrel56/json-schema#68]
I have a main schema file with refrences to external schema (where I define common types)
```
 { "$id": "/main-schema.json"
  "properties": {"myProperty": {"$ref": "types.json#/$defs/myType"}}
  }
```
external schema for common types "types.json":
```
{  "$id": "/types.json"
   "$defs": {"myType": {"type": []}}    <-- wrong 'type' here, should be 1+ type definition
}
```

When I have an error in any of the schema files, I have a little information about the origin of the error. There is `Error.getInstanceLocation()` which returns something like `/$defs/myType`. It is OK when the whole schema is located in one single file. But in my case I have 2 files, so will be good to have an extra information about file with incorrect definition.   I understand that it is hard  or impossible to provide filename, so the $Id of the schema with error is good alternative.

**Comment by harrel56** [comment]
Hmm, actually the affected schema URI is contained in exception message, e.g. `Schema [a/b/subschema.json] failed to validate against meta-schema [https://json-schema.org/draft/2020-12/schema]`. I could add schema URI as a field in `InvalidSchemaException` - would that solve your use case?

**Comment by kool79** [comment]
Thank for pointing this out.  It definetly solves my case. 
(In my I catched the exeption and print only content of the ex.getErrors())
