### ISSUE TITLE
Feature request: Add support for draft 2019-09

### ISSUE THREAD

**Issue by kool79** [harrel56/json-schema#71]
While the 2020-12 is the recent standard version, it does not support older 2019-09 draft. There are many schemas which cannot be natively processed by current library. It is not possible to migrate them to 2020-12 as well (even if they are fully compatible by syntax and dont use old keywords), becase other tools does not understand 2020-12.

Is it easy (with minimal effort) to add support for 2019-09? It OK if it will not support 2019-specific features

**Comment by harrel56** [comment]
If supporting 2019 specification features is not required then I'm not sure what is the subject of this issue? Is parsing schemas written in old spec failing? Where exactly problems occur when trying to use old schemas? If you could provide some kind of example of such schemas it would be really helpful.

One thing that I'm sure that I won't be able to support is handling multiple dialects in scope of one validator.

But implementing a full support for 2019 spec is something that I thought about - it's rather a big change so it won't be completed in the nearest future (i think). But if it's required by some users then it will hopefully and eventually happen
