### ISSUE TITLE
Paths and property names with slashes

### ISSUE THREAD

**Issue by holgpar** [harrel56/json-schema#94]
Hi,

the `EvaluationItem` class provides fields like `evaluationPath` and `instanceLocation` which work similar to JSON path expressions.
However, in some cases it is not possible to map these paths to actual location in the schema or instance: Slashes are used as separators, but slashes can also appear in property names in JSON. This introduces an ambiguity.

If paths are just used for error messages, that might be okay, but it is an issue when setting defaults according to defined `default` annotations in the schema.

One could consider to:
- provide actual JSON path expression (here dots are the separators and they can be escaped as follows: `.[something.with.dots]`
- provide paths as List of elements which can be of type property access or (list) item access

what do you think?

**Comment by holgpar** [comment]
Oh, I was not even aware that JSON pointers are a standard. Good to know. And yes, any defined escaping would do the job.

**Comment by harrel56** [comment]
Not encoding every JSON pointer has more significant impact than I thought. It may override some schemas during registration process. Gonna try to patch that up ASAP. That was a really nice find - thanks for your feedback!
